ci: cache built image

diff --git a/.github/workflows/chat.yml b/.github/workflows/chat.yml
--- a/.github/workflows/chat.yml
+++ b/.github/workflows/chat.yml
@@ -95,7 +95,7 @@ jobs:
 
       - name: Run test
         working-directory: chat
-        run: pnpm test:e2e
+        run: pnpm test
 
   e2e-test:
     runs-on: ubuntu-22.04
@@ -133,10 +133,10 @@ jobs:
 
       - name: Run test
         working-directory: chat
-        run: pnpm test
+        run: pnpm test:e2e
 
   build:
-    if: github.event_name == 'push'
+    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[skip build]') == false
 
     needs:
       - lint
@@ -173,17 +173,17 @@ jobs:
 
             refs/heads/production)
               echo "TAGS=\
-              ghcr.io/${{ github.repository }}-chat:staging-latest, \
-              ghcr.io/${{ github.repository }}-chat:staging-${{ github.sha }}" >> $GITHUB_OUTPUT
+              ghcr.io/${{ github.repository }}-chat:latest, \
+              ghcr.io/${{ github.repository }}-chat:${{ github.sha }}" >> $GITHUB_OUTPUT
               ;;
 
             *)
-              echo "This branch can't be built"
+              echo "This branch can't be built";
+              exit 1;
               ;;
           esac
 
       - name: Build and push
-        if: steps.tags.outputs.TAGS != ''
         uses: docker/build-push-action@v4
         with:
           push: true
diff --git a/.github/workflows/core.yaml b/.github/workflows/core.yaml
--- a/.github/workflows/core.yaml
+++ b/.github/workflows/core.yaml
@@ -82,7 +82,7 @@ jobs:
         run: go test ./... -cover
 
   build:
-    if: github.event_name == 'push'
+    if: github.event_name == 'push' && contains(github.event.head_commit.message, '[skip build]') == false
 
     needs:
       - lint
@@ -118,17 +118,17 @@ jobs:
 
             refs/heads/production)
               echo "TAGS=\
-              ghcr.io/${{ github.repository }}-core:staging-latest, \
-              ghcr.io/${{ github.repository }}-core:staging-${{ github.sha }}" >> $GITHUB_OUTPUT
+              ghcr.io/${{ github.repository }}-core:latest, \
+              ghcr.io/${{ github.repository }}-core:${{ github.sha }}" >> $GITHUB_OUTPUT
               ;;
 
             *)
-              echo "This branch can't be built"
+              echo "This branch can't be built";
+              exit 1;
               ;;
           esac
 
       - name: Build and push
-        if: steps.tags.outputs.TAGS != ''
         uses: docker/build-push-action@v4
         with:
           push: true
