update: login validation and connect with sever

diff --git a/.github/workflows/chat.yml b/.github/workflows/chat.yml
--- a/.github/workflows/chat.yml
+++ b/.github/workflows/chat.yml
@@ -4,11 +4,33 @@ on:
   push:
     branches:
       - main
+      - development
+      - production
     paths:
+      - .github/workflows/chat.yml
       - chat/**
+      - '!chat/.vscode/**'
+      - '!chat/docs/**'
+      - '!chat/.editorconfig'
+      - '!chat/.gitignore'
+      - '!chat/**.md'
+  pull_request:
+    branches:
+      - main
+    paths:
+      - .github/workflows/chat.yml
+      - chat/**
+      - '!chat/.vscode/**'
+      - '!chat/docs/**'
+      - '!chat/.editorconfig'
+      - '!chat/.gitignore'
+      - '!chat/**.md'
+
+env:
+  WORKDIR: chat
 
 jobs:
-  test:
+  lint:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
@@ -35,20 +57,109 @@ jobs:
             ${{ runner.os }}-pnpm-store-
 
       - name: Install dependencies
-        working-directory: chat
+        working-directory: ${{ env.WORKDIR }}
+        run: pnpm i
+
+      - name: Lint
+        working-directory: ${{ env.WORKDIR }}
+        run: pnpm lint
+
+  lint-dockerfile:
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - uses: hadolint/hadolint-action@v3.1.0
+        with:
+          dockerfile: ${{ env.WORKDIR }}/Dockerfile
+
+  unit-test:
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Use pNPM
+        uses: pnpm/action-setup@v2
+        with:
+          version: 7
+          run_install: false
+
+      - name: Get pnpm store directory
+        id: pnpm-cache
+        shell: bash
+        run: |
+          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
+
+      - name: Setup pnpm cache
+        uses: actions/cache@v3
+        with:
+          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
+          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-pnpm-store-
+
+      - name: Install dependencies
+        working-directory: ${{ env.WORKDIR }}
         run: pnpm i
 
       - name: Create cofig
-        working-directory: chat
+        working-directory: ${{ env.WORKDIR }}
         run: cp .env.example .env
 
       - name: Run test
-        working-directory: chat
+        working-directory: ${{ env.WORKDIR }}
         run: pnpm test
 
+  e2e-test:
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Use pNPM
+        uses: pnpm/action-setup@v2
+        with:
+          version: 7
+          run_install: false
+
+      - name: Get pnpm store directory
+        id: pnpm-cache
+        shell: bash
+        run: |
+          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
+
+      - name: Setup pnpm cache
+        uses: actions/cache@v3
+        with:
+          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
+          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+          restore-keys: |
+            ${{ runner.os }}-pnpm-store-
+
+      - name: Install dependencies
+        working-directory: ${{ env.WORKDIR }}
+        run: pnpm i
+
+      - name: Create cofig
+        working-directory: ${{ env.WORKDIR }}
+        run: cp .env.example .env
+
+      - name: Run test
+        working-directory: ${{ env.WORKDIR }}
+        run: pnpm test:e2e
+
   build:
+    if: |
+      github.event_name == 'push' &&
+      contains(fromJson('["refs/heads/development", "refs/heads/production"]'), github.ref)
+
     needs:
-      - test
+      - lint
+      - lint-dockerfile
+      - unit-test
+      - e2e-test
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
@@ -72,27 +183,29 @@ jobs:
         run: |
           case ${{ github.ref }} in
 
-            refs/heads/main)
+            refs/heads/development)
               echo "TAGS=\
-              ghcr.io/${{ github.repository }}-chat:staging-latest, \
-              ghcr.io/${{ github.repository }}-chat:staging-${{ github.sha }}" >> $GITHUB_OUTPUT
+              ghcr.io/${{ github.repository }}-$WORKDIR:staging-latest, \
+              ghcr.io/${{ github.repository }}-$WORKDIR:staging-${{ github.sha }}" >> $GITHUB_OUTPUT
               ;;
 
             refs/heads/production)
               echo "TAGS=\
-              ghcr.io/${{ github.repository }}-chat:staging-latest, \
-              ghcr.io/${{ github.repository }}-chat:staging-${{ github.sha }}" >> $GITHUB_OUTPUT
+              ghcr.io/${{ github.repository }}-$WORKDIR:latest, \
+              ghcr.io/${{ github.repository }}-$WORKDIR:${{ github.sha }}" >> $GITHUB_OUTPUT
               ;;
 
             *)
-              echo "This branch can't be built"
+              echo "This branch can't be built";
+              exit 1;
               ;;
           esac
 
       - name: Build and push
-        if: steps.tags.outputs.TAGS != ''
         uses: docker/build-push-action@v4
         with:
           push: true
-          context: ./chat
+          context: ./${{ env.WORKDIR }}
           tags: ${{ steps.tags.outputs.TAGS }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
